### ISSUE TITLE
Zoom subdomains

### ISSUE THREAD

**Issue by CarsonF** [seanstar12/zoom-close#1]
Can you match wildcard for zoom subdomains?

My link is:
```
https://tsco.zoom.us/j/9886632336
```

**Comment by chriscannon** [comment]
Hey I made a pull request #2 to address this issue. Hope it helps!

**Comment by seanstar12** [comment]
Looks good to me. I'll push out an updated build to the chrome extension store.

**Comment by chriscannon** [comment]
Awesome thanks!
